### PR TITLE
Support Flyway 7.0 and 7.1

### PR DESCRIPTION
**Pull request by tomix26**

### CODE REVIEW

**Comment by trecloux** [comment]
@tomix26 Spring 2.4.0 linked to Flyway 7 was just [released](https://github.com/spring-projects/spring-boot/releases/tag/v2.4.0).

Could it be possible to release the library in the next days ?

**Comment by tomix26** [comment]
> @tomix26 Spring 2.4.0 linked to Flyway 7 was just [released](https://github.com/spring-projects/spring-boot/releases/tag/v2.4.0).
> 
> Could it be possible to release the library in the next days ?

Yes, sure. Sorry for the delay, a lot of work. I'll try to release it today.

**Comment by tomix26** [comment]
> > @tomix26 Spring 2.4.0 linked to Flyway 7 was just [released](https://github.com/spring-projects/spring-boot/releases/tag/v2.4.0).
> > Could it be possible to release the library in the next days ?
> 
> Yes, sure. Sorry for the delay, a lot of work. I'll try to release it today.

Done

**Comment by trecloux** [comment]
Thanks a lot ;-)

**Pull request merged**
